# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7374d94f3dae29853094b222c943efbbcc1ce45b6899fbf4b9e1779ece1f598a38d044b6ac12108070dc3fa5d6e2560a4ae82b40ca5655a37c098171ec5aa3e0

test:
  secret_key_base: 93051e284f5b6ef84e52bb3b8749be68ed5bbd810276f5f623baab9c993aa05090e23550dcea95ec186d3f01b79133f9016bf7b0575b79058bbe21a465e3108a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
